// The consumer half of ante, in TypeScript — the exact counterpart of
// `ante_core::proof` / `ante_core::pow`. An app author drops this in to verify
// proofs client-side, or the bundled UI uses it for the "check a proof" panel.
//
// The cross-implementation vector in test/ante-proof.test.ts is generated by
// Rust; if this file and `ante-core` ever disagree, that test fails.

import { blake3 } from "@noble/hashes/blake3.js";
import { ed25519 } from "@noble/curves/ed25519.js";

import { asBytes, asNumber, asString, cborDecode, type CborValue, mapGet } from "./cbor";
import { leadingZeroBits } from "./pow";
import { base58, concatBytes, u32le, u64le } from "./util";

const CHALLENGE_CONTEXT = new TextEncoder().encode("ante:pow-challenge:v1");
const SIGNING_CONTEXT = new TextEncoder().encode("ante:proof-signature:v1");

export const MAX_PURPOSE_BYTES = 256;

/// The purpose string the identity-level registry pins. A proof for this is a
/// portable "this identity is worth at least N bits" statement.
export const IDENTITY_LEVEL_PURPOSE = "ante:identity-level:v2";

export interface AnteProof {
  identityVk: Uint8Array; // 32 bytes
  purpose: string;
  nonce: number;
  ts: number;
  signature: Uint8Array; // 64 bytes
}

/// `ante_core::pow::challenge_bytes`: the preimage a nonce is ground against.
export function challengeBytes(purpose: string, identityVk: Uint8Array): Uint8Array {
  const p = new TextEncoder().encode(purpose);
  return concatBytes(CHALLENGE_CONTEXT, u32le(p.length), p, identityVk);
}

/// `ante_core::proof::signing_bytes`: the preimage the identity signs.
function signingBytes(proof: AnteProof): Uint8Array {
  const p = new TextEncoder().encode(proof.purpose);
  return concatBytes(
    SIGNING_CONTEXT,
    proof.identityVk,
    u32le(p.length),
    p,
    u64le(proof.nonce),
    u64le(proof.ts),
  );
}

/// Leading-zero bits the proof's nonce demonstrates. Ground truth — a pure
/// function of `(purpose, identity_vk, nonce)`.
export function proofBits(proof: AnteProof): number {
  const digest = blake3(concatBytes(challengeBytes(proof.purpose, proof.identityVk), u64le(proof.nonce)));
  return leadingZeroBits(digest);
}

export type VerifyResult = { ok: true; bits: number } | { ok: false; error: string };

/// Verify a proof against a `minBits` policy. On success, returns the bits the
/// proof actually demonstrates (>= minBits).
export function verifyAnteProof(proof: AnteProof, minBits: number): VerifyResult {
  if (proof.identityVk.length !== 32) {
    return { ok: false, error: "identity_vk must be 32 bytes" };
  }
  const purposeLen = new TextEncoder().encode(proof.purpose).length;
  if (purposeLen === 0 || purposeLen > MAX_PURPOSE_BYTES) {
    return { ok: false, error: `purpose must be 1..=${MAX_PURPOSE_BYTES} bytes` };
  }

  const bits = proofBits(proof);
  if (bits < minBits) {
    return { ok: false, error: `proof demonstrates ${bits} bits, need ${minBits}` };
  }

  let signatureOk = false;
  try {
    signatureOk = ed25519.verify(proof.signature, signingBytes(proof), proof.identityVk);
  } catch {
    signatureOk = false;
  }
  if (!signatureOk) {
    return { ok: false, error: "signature does not verify for this identity" };
  }

  return { ok: true, bits };
}

/// Decode an `AnteProof` from the CBOR the delegate returns
/// (`AnteResponse::Committed.proof`, i.e. `commit()`'s `bytes`).
export function decodeAnteProof(cbor: Uint8Array): AnteProof {
  return decodeAnteProofValue(cborDecode(cbor));
}

/// Decode an `AnteProof` already sitting inside a larger decoded CBOR value —
/// e.g. the `proof` field of an entry you read from your contract's state.
export function decodeAnteProofValue(value: CborValue | undefined): AnteProof {
  const proof: AnteProof = {
    identityVk: asBytes(mapGet(value, "identity_vk")),
    purpose: asString(mapGet(value, "purpose")),
    nonce: asNumber(mapGet(value, "nonce")),
    ts: asNumber(mapGet(value, "ts")),
    signature: asBytes(mapGet(value, "signature")),
  };
  if (proof.identityVk.length !== 32) throw new Error("identity_vk must be 32 bytes");
  if (proof.signature.length !== 64) throw new Error("signature must be 64 bytes");
  return proof;
}

/// The wire form of an `AnteProof` as a CBOR value — the inverse of
/// `decodeAnteProof`. Embed it in your own record before `cborEncode`:
///
///   cborEncode({ name, text, proof: anteProofToCborValue(proof) })
///
/// Field names and order match `ante_core::proof::AnteProof`, so `ante-core`
/// on the contract side decodes it directly. `identity_vk` / `signature` go
/// out as CBOR arrays of bytes, which is what ciborium emits for `[u8; N]`.
export function anteProofToCborValue(proof: AnteProof): CborValue {
  return {
    identity_vk: Array.from(proof.identityVk),
    purpose: proof.purpose,
    nonce: proof.nonce,
    ts: proof.ts,
    signature: Array.from(proof.signature),
  };
}

/// Short, stable handle for an identity — bs58 of the first 8 key bytes.
/// Matches `ante_core::fingerprint`. Not a security boundary.
export function fingerprint(identityVk: Uint8Array): string {
  return base58(identityVk.slice(0, 8));
}
