// GENERATED by scripts/gen-embedded.sh — placeholder; scripts/sync-delegate.sh
// overwrites it. Restore with `git checkout client/src/embedded.ts`.
export const ANTE_DELEGATE_WASM_B64 = "";
export const ANTE_DELEGATE_KEY_BYTES: number[] = [];
export const ANTE_DELEGATE_CODE_HASH_BYTES: number[] = [];
export const ANTE_REGISTRY_CONTRACT_ID = "";
export function delegateEmbedded(): boolean {
  return (
    ANTE_DELEGATE_WASM_B64.length > 0 &&
    ANTE_DELEGATE_KEY_BYTES.length === 32 &&
    ANTE_DELEGATE_CODE_HASH_BYTES.length === 32
  );
}
