#!/usr/bin/env bash
# Regenerate client/src/embedded.ts from the built delegate WASM and the
# recorded registry contract id.
#
#   gen-embedded.sh <delegate.wasm> [<registry-instance-id>]
#
# If the registry id is omitted, the one currently in embedded.ts is kept.
#
# embedded.ts is gitignored — it holds a ~370 KB base64 blob that re-keys on
# every delegate change. A fresh checkout has none until `npm install` copies
# embedded.stub.ts over (the `prepare` script), which is enough for `tsc` /
# `vitest`; this script writes the real one.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/client/src/embedded.ts"
WASM="${1:?usage: gen-embedded.sh <delegate.wasm> [registry-id]}"

KEYINFO="$(cargo run -q --manifest-path "$REPO_ROOT/Cargo.toml" -p delegate-key -- "$WASM")"
# Match the field name exactly — the tool also prints key_hex / code_hash_hex.
KEY="$(echo "$KEYINFO" | awk '$1 == "key" {print $2}')"
CODE_HASH="$(echo "$KEYINFO" | awk '$1 == "code_hash" {print $2}')"
B64="$(base64 -w0 < "$WASM" 2>/dev/null || base64 < "$WASM" | tr -d '\n')"

if [ "${2-}" != "" ]; then
  REGISTRY_ID="$2"
else
  REGISTRY_ID="$(grep -oE 'ANTE_REGISTRY_CONTRACT_ID = "[^"]*"' "$OUT" | sed 's/.*"\(.*\)"/\1/' || true)"
fi

cat > "$OUT" <<EOF
// GENERATED by scripts/gen-embedded.sh — do not edit by hand.
//
// The ante delegate is the same WASM for every app, so it's embedded here once
// rather than injected per-app. The registry id is the canonical
// identity-level registry instance.

export const ANTE_DELEGATE_WASM_B64 =
  "$B64";
export const ANTE_DELEGATE_KEY_BYTES: number[] = $KEY;
export const ANTE_DELEGATE_CODE_HASH_BYTES: number[] = $CODE_HASH;

/// Base58 instance id of the canonical ante identity-level registry, or "".
export const ANTE_REGISTRY_CONTRACT_ID = "$REGISTRY_ID";

export function delegateEmbedded(): boolean {
  return (
    ANTE_DELEGATE_WASM_B64.length > 0 &&
    ANTE_DELEGATE_KEY_BYTES.length === 32 &&
    ANTE_DELEGATE_CODE_HASH_BYTES.length === 32
  );
}
EOF

# Keep deployments.json's delegate lineage in step, as a side effect of the
# build rather than as something someone has to remember. The publish scripts
# already do this for contracts, on the principle that a predecessor which is
# not recorded is state a future migration cannot reach — and the delegate is
# the one whose lineage strands people's IDENTITIES, so it is the last place to
# rely on memory. Idempotent: only moves `current` aside when it really changed.
KEY_HEX="$(echo "$KEYINFO" | awk '$1 == "key_hex" {print $2}')"
CODE_HASH_HEX="$(echo "$KEYINFO" | awk '$1 == "code_hash_hex" {print $2}')"
python3 - "$REPO_ROOT/deployments.json" "$KEY_HEX" "$CODE_HASH_HEX" <<'PYEOF'
import json, sys
path, key, code_hash = sys.argv[1:4]
d = json.load(open(path))
cur = d["delegate"].get("current", {})
if cur.get("key") and cur["key"] != key:
    sup = d["delegate"].setdefault("superseded", [])
    if not any(e.get("key") == cur["key"] for e in sup):
        sup.insert(0, {k: cur[k] for k in ("key", "codeHash") if k in cur})
        print(f"  lineage: delegate {cur['key'][:16]}… -> superseded")
d["delegate"]["current"] = {"key": key, "codeHash": code_hash}
json.dump(d, open(path, "w"), indent=2)
open(path, "a").write("\n")
PYEOF

echo "wrote $OUT"
echo "  delegate: $(wc -c < "$WASM") bytes  key ${KEY:0:24}…"
echo "  registry: ${REGISTRY_ID:-<none>}"
