#!/usr/bin/env bash
# Regenerate client/src/embedded.ts from the built delegate WASM and the
# recorded registry contract id.
#
#   gen-embedded.sh <delegate.wasm> [<registry-instance-id>]
#
# If the registry id is omitted, the one currently in embedded.ts is kept. The
# generated file is what @ante/client uses at runtime; a fresh checkout ships a
# placeholder so `tsc` / `vitest` pass without a build.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/client/src/embedded.ts"
WASM="${1:?usage: gen-embedded.sh <delegate.wasm> [registry-id]}"

KEYINFO="$(cargo run -q --manifest-path "$REPO_ROOT/Cargo.toml" -p delegate-key -- "$WASM")"
KEY="$(echo "$KEYINFO" | awk '/^key/ {print $2}')"
CODE_HASH="$(echo "$KEYINFO" | awk '/^code_hash/ {print $2}')"
B64="$(base64 -w0 < "$WASM" 2>/dev/null || base64 < "$WASM" | tr -d '\n')"

if [ "${2-}" != "" ]; then
  REGISTRY_ID="$2"
else
  REGISTRY_ID="$(grep -oE 'ANTE_REGISTRY_CONTRACT_ID = "[^"]*"' "$OUT" | sed 's/.*"\(.*\)"/\1/' || true)"
fi

cat > "$OUT" <<EOF
// GENERATED by scripts/gen-embedded.sh — do not edit by hand.
//
// The ante delegate is the same WASM for every app, so it's embedded here once
// rather than injected per-app. The registry id is the canonical
// identity-level registry instance.

export const ANTE_DELEGATE_WASM_B64 =
  "$B64";
export const ANTE_DELEGATE_KEY_BYTES: number[] = $KEY;
export const ANTE_DELEGATE_CODE_HASH_BYTES: number[] = $CODE_HASH;

/// Base58 instance id of the canonical ante identity-level registry, or "".
export const ANTE_REGISTRY_CONTRACT_ID = "$REGISTRY_ID";

export function delegateEmbedded(): boolean {
  return (
    ANTE_DELEGATE_WASM_B64.length > 0 &&
    ANTE_DELEGATE_KEY_BYTES.length === 32 &&
    ANTE_DELEGATE_CODE_HASH_BYTES.length === 32
  );
}
EOF

echo "wrote $OUT"
echo "  delegate: $(wc -c < "$WASM") bytes  key ${KEY:0:24}…"
echo "  registry: ${REGISTRY_ID:-<none>}"
