import { describe, expect, it } from "vitest";

import {
  challengeBytes,
  decodeAnteProof,
  fingerprint,
  proofBits,
  verifyAnteProof,
} from "../src/ante-proof";
import { grind, powBits } from "../src/pow";
import { bytesToHex, hexToBytes } from "../src/util";

// Generated by `ante-core` (a throwaway example binding pow::grind +
// AnteProof::create). Regenerate if the wire format or domain-separation
// layout changes — a mismatch here means the TS and Rust halves have drifted.
const VECTOR = {
  seedHex: "2a".repeat(32),
  vkHex: "197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d61",
  purpose: "ante:identity-level:v1",
  ts: 1_726_000_000_000,
  nonce: 35609,
  achievedBits: 16,
  challengeHex:
    "616e74653a706f772d6368616c6c656e67653a763116000000616e74653a6964656e746974792d6c6576656c3a7631197f6b23e16c8532c6abc838facd5ea789be0c76b2920334039bfa8b3d368d61",
  proofCborHex:
    "a56b6964656e746974795f766b98201819187f186b182318e1186c1885183218c618ab18c8183818fa18cd185e18a7188918be0c187618b2189203183403189b18fa188b183d1836188d186167707572706f736576616e74653a6964656e746974792d6c6576656c3a7631656e6f6e6365198b196274731b00000191dd9dec00697369676e6174757265984018f6188b07189c18d5182b184518e8187f185e187118a418e618cc189e18ff1897185f189e1838188018ef186d1860188f18c50f18de18e618f118de186e189d186518510f1834182f189a1869189e0d18d0185a18cc189a188418ad14184b187e184a18bc186e1858121872189718ea18ad182718e418970a",
};

describe("challenge layout matches ante-core::pow", () => {
  it("challenge_bytes reproduces the Rust bytes", () => {
    const got = challengeBytes(VECTOR.purpose, hexToBytes(VECTOR.vkHex));
    expect(bytesToHex(got)).toBe(VECTOR.challengeHex);
  });

  it("the recorded nonce grades to the recorded bits", () => {
    const challenge = hexToBytes(VECTOR.challengeHex);
    expect(powBits(challenge, VECTOR.nonce)).toBe(VECTOR.achievedBits);
  });
});

describe("verifyAnteProof matches ante-core::proof::verify", () => {
  const proof = decodeAnteProof(hexToBytes(VECTOR.proofCborHex));

  it("decodes the Rust-produced CBOR", () => {
    expect(bytesToHex(proof.identityVk)).toBe(VECTOR.vkHex);
    expect(proof.purpose).toBe(VECTOR.purpose);
    expect(proof.nonce).toBe(VECTOR.nonce);
    expect(proof.ts).toBe(VECTOR.ts);
    expect(proof.signature).toHaveLength(64);
  });

  it("grades to the achieved bits", () => {
    expect(proofBits(proof)).toBe(VECTOR.achievedBits);
  });

  it("verifies at and below the achieved bar", () => {
    expect(verifyAnteProof(proof, VECTOR.achievedBits)).toEqual({
      ok: true,
      bits: VECTOR.achievedBits,
    });
    expect(verifyAnteProof(proof, 8).ok).toBe(true);
  });

  it("rejects a higher bar as insufficient work, without a signature error", () => {
    const r = verifyAnteProof(proof, 24);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error).toContain("need 24");
  });

  it("rejects a tampered timestamp", () => {
    const r = verifyAnteProof({ ...proof, ts: proof.ts + 1 }, 8);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error).toContain("signature");
  });

  it("rejects a tampered purpose", () => {
    expect(verifyAnteProof({ ...proof, purpose: "something-else" }, 8).ok).toBe(false);
  });

  it("fingerprint matches the first 8 key bytes", () => {
    expect(fingerprint(proof.identityVk)).toBe(fingerprint(hexToBytes(VECTOR.vkHex)));
    expect(fingerprint(proof.identityVk).length).toBeGreaterThan(0);
  });
});

describe("grinder", () => {
  it("finds a nonce clearing a low bar for an arbitrary challenge", () => {
    const challenge = challengeBytes("test:purpose", new Uint8Array(32).fill(3));
    const nonce = grind(challenge, 10);
    expect(powBits(challenge, nonce)).toBeGreaterThanOrEqual(10);
  });
});
